events { worker_connections 1024; }

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Static files
    location / { try_files $uri /index.html; }

    # Proxy para IPTV streams HTTP -> HTTPS (evita mixed content)
    location /hls-proxy/ {
      resolver 8.8.8.8 valid=30s;
      set $backend "http://181.224.200.5:2277";
      
      if ($arg_host) { set $backend $arg_host; }
      
      rewrite ^/hls-proxy/(.*) /$1 break;
      
      proxy_pass $backend;
      proxy_http_version 1.1;
      proxy_set_header Host $proxy_host;
      proxy_set_header User-Agent "Mozilla/5.0";
      proxy_set_header Connection "";
      
      add_header Access-Control-Allow-Origin *;
      
      proxy_buffering off;
      proxy_cache off;
      proxy_read_timeout 3600s;
    }

    # Proxy para IPTV 190
    location /hls-proxy-190/ {
      resolver 8.8.8.8 valid=30s;
      rewrite ^/hls-proxy-190/(.*) /$1 break;
      proxy_pass http://190.108.83.69:8000;
      proxy_http_version 1.1;
      proxy_set_header Host "190.108.83.69:8000";
      proxy_set_header User-Agent "Mozilla/5.0";
      add_header Access-Control-Allow-Origin *;
      proxy_buffering off;
      proxy_cache off;
      proxy_read_timeout 3600s;
    }
  }
}
